# Generated by Django 4.0.4 on 2023-12-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_order_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(null=True, through='restaurant.OrderItem', to='restaurant.menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='placing', max_length=30),
        ),
    ]
