# Generated by Django 4.0.4 on 2023-12-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_shippingdetails_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='additional',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
