# Generated by Django 4.2.7 on 2023-12-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="logo",
            field=models.ImageField(default=None, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="title",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name="order",
            name="menu_items",
            field=models.ManyToManyField(
                through="restaurant.OrderItem", to="restaurant.menu"
            ),
        ),
    ]
